version: "3"
services:
  web:
    image: atsushikoga/centos-7.4_apache-2.4_php:7.2
    ports: 
      - "80:80"
    privileged: true
    links:
      - db
    volumes:
      - "./https/:/var/www/html"
    container_name: "apache-php"
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: pgsql_local
      POSTGRES_PASSWORD: ewpAWB#P3w
    ports:
      - "5432:5432"
    container_name: "psql"
  selenium:
    image: selenium/standalone-chrome:latest